services:
    rplidar:
        image: eduartrobotik/nav2:1.2.0
        container_name: slam-tool-box-1.1.0
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
            - CYCLONEDDS_URI=/home/user/ros/launch_content/cyclone_dds_profile.xml
            - MAP_FILE=${MAP_FILE}
            - FILTER_FILE=${FILTER_FILE}
            - ROS_DOMAIN_ID=${ROS_DOMAIN_ID:-0}
        network_mode: "host"
        devices:
            - '/dev:/dev'
        group_add:
            - dialout
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch slam.launch.py use_sim_time:=${EDU_USE_SIM_TIME:-false}'
        volumes:
            - './launch_content:/home/user/ros/launch_content:r'
            