services:
    rplidar:
        image: eduartrobotik/nav2:1.1.0
        container_name: slam-tool-box-1.1.0
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - RMW_IMPLEMENTATION=${RMW_IMPLEMENTATION}
            - CYCLONEDDS_URI=/home/user/ros/launch_content/cyclone_dds_profile.xml                 
        network_mode: "host"
        devices:
            - '/dev:/dev'
        group_add:
            - dialout
        command: bash -c 'cd /home/user/ros/launch_content; ros2 launch slam.launch.py'
        volumes:
            - './launch_content:/home/user/ros/launch_content:r'
            