version: "2.4"

services:
    edu-web-joy:
        image: eduartrobotik/eduard-web-joy:0.2.0
        container_name: eduard-web-joy-0.2.0
        # debugging command for layer 2 network access
        # command: bash -c "sudo apt-get update && sudo apt-get install -y iproute2 net-tools && ip addr && printenv && source /home/user/ros/install/setup.bash && ros2 topic list && ros2 daemon start && sudo netstat -gn && ros2 launch /home/user/ros/src/edu_web_joy/edu_web_joy/launch/server.launch.py"        
        restart: on-failure
        privileged: true
        ipc: host
        pid: host
        mem_limit: 150mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard
        networks:
            - proxy-redirect
            # - zzz_layer2_net1
        volumes:
            - './publish/:/publish/'
            - './cfg-data/:/cfg-data/'
        ports:
            - "8888:8888"

networks:
    proxy-redirect:
        external: true
    # zzz_layer2_net1:
    #     name: zzz_layer2_net1
    #     external: true
