services:
    database:
        image: mongo:4.4
        hostname: mongo-db
        network_mode: host
        expose:
            - "27017"
        command: --bind_ip_all
    broker:
        image: fiware/orion
        hostname: orion
        network_mode: host
        ports:
            - "1026:1026"
        command: -dbhost mongo-db
        depends_on:
            - database
    visual-ros:
        image: eduartrobotik/eduart-nodered:0.1.0
        network_mode: host
        ports:
            - "1880:1880"
            - "9229:9229"
        command: node /usr/bin/node-red
        depends_on:
            - broker

