/**:
  ros__parameters:
    filter1:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.3
        max_y: 0.3
        max_z: 0.5
        min_x: -0.3
        min_y: -0.3
        min_z: -0.5
